# Generated by Django 3.2 on 2021-05-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='DateOfJoinig',
            field=models.CharField(max_length=100),
        ),
    ]
