# Generated by Django 3.2 on 2021-05-05 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0002_alter_employees_dateofjoinig'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='DateOfJoinig',
            new_name='DateOfJoining',
        ),
    ]
